### ISSUE TITLE
Ability to create Luau buffer from bytes / get bytes contents

### ISSUE THREAD

**Issue by filiptibell** [mlua-rs/mlua#378]
The Luau `buffer` type is currently a bit difficult to use with mlua since it is implemented as userdata and there is no direct access to its bytes from rust.

- I would like to to create a buffer userdata directly from `&[u8]` without extra overhead
- I would like to also access the raw bytes of ex. a buffer userdata given as an argument to a function from `lua.create_function`

Would it be possible to implement these two things in mlua?
Maybe `lua.create_buffer` and `LuaValue::as_buffer_bytes` or similar APIs?

**Comment by khvzak** [comment]
I'll take a look to it! I'm not sure it worth to introduce a new datatype for buffer, but I'll see what optional I can offer.

**Comment by khvzak** [comment]
I was working on the issue recently and can say that unfortunately it's impossible (yet) to provide _zerocopy_ access to raw bytes using Rust safe api.
The problem is that the underlying data buffer is _mutable_ and can be changed anytime, so holding a readonly reference to data while still having ability to modify it simply break Rust [aliasing rules](https://doc.rust-lang.org/nomicon/aliasing.html).

A simple example:
```rust
fn access_buffer(lua: &Lua, buf: Buffer) {
    let a: &[u8] = buf.as_ref(); // let's say the buffer has "abc" string
    lua.load("buffer.writestring(buf, 2, \"d")").exec().unwrap();
   // `a` now points to "abd" which must be impossible.
}
```

To make safe api possible buffer must have ability to be switched into readonly mode without switching back. Sort of `buffer.freeze(buf)`.

Creating buffer is totally fine operation.

**Comment by filiptibell** [comment]
> unfortunately it's impossible (yet) to provide zerocopy access to raw bytes using Rust safe api

That is unfortunate 😔 but I think it would be okay to have an api that gives a `Vec<u8>` too. In a lot of cases we need a Vec anyway because we are sending data to some other thread / passing data to tokio futures that are `'static` and `&'lua [u8]` would cause issues there.

**Comment by khvzak** [comment]
I pushed a commit https://github.com/mlua-rs/mlua/commit/fa217d3706ebebfd1519743c3e620a940c218967 to add extended bytes support.
You can access raw bytes using `BString` type
