### ISSUE TITLE
Can Lua symbols be exported on Windows?

### ISSUE THREAD

**Issue by CppCXY** [mlua-rs/mlua#451]
If I want to debug Lua scripts on Windows, at least, the process needs to export Lua symbols. Is there a way to do this?

**Comment by khvzak** [comment]
> the process needs to export Lua symbols.

could you provide more information?

**Comment by CppCXY** [comment]
> > the process needs to export Lua symbols.
> 
> could you provide more information?

If I want to debug mlua's Lua scripts, mlua must export symbols that can be dynamically loaded by external DLLs.

**Comment by khvzak** [comment]
> mlua must export symbols that can be dynamically loaded by external DLLs.

mlua is just a library. Should your app export symbols instead?

I'm not familiar (never developed) with windows. On macos and linux you can export symbols by creating `.cargo/config.toml` with the content:
```
[target.<your arch>]
rustflags = ["-C", "link-args=-rdynamic"]
```

I'm not sure will this approach work on windows or not. 
When last time I checked windows even does not support dynamic symbols lookup (eg passing `-undefined=dynamic_lookup` for modules) and require having Lua VM as dll rather than statically linked to the app.

**Comment by CppCXY** [comment]
Thanks
